spring:
  application:
    name: seat-booking-management
  
  profiles:
    active: dev
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true
        use_sql_comments: true
    open-in-view: false
  
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
  
app:
  admin:
    username: ${ADMIN_USERNAME:admin@concert.com}
    password: ${ADMIN_PASSWORD:Pwd@1234}
  staff:
    username: ${STAFF_USERNAME:staff@concert.com}
    password: ${STAFF_PASSWORD:Pwd@1234}
  customer:
    username: ${CUSTOMER_USERNAME:customer@concert.com}
    password: ${CUSTOMER_PASSWORD:Pwd@1234}

logging:
  level:
    com.concert: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

---
spring:
  config:
    activate:
      on-profile: dev
  
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: seat_booking
    password: seat_booking
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  jpa:
    show-sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG

---
spring:
  config:
    activate:
      on-profile: docker
  
  datasource:
    url: jdbc:oracle:thin:@oracle-db:1521:XE
    username: seat_booking
    password: seat_booking
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
  
  jpa:
    show-sql: false

logging:
  level:
    com.concert: INFO
    org.hibernate.SQL: WARN

---
spring:
  config:
    activate:
      on-profile: test
  
  datasource:
    # TestContainers will override these values
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: test
    password: test
    driver-class-name: oracle.jdbc.OracleDriver
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  
  flyway:
    enabled: false

logging:
  level:
    org.testcontainers: INFO
    com.concert: DEBUG