-- Create users table
CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) NOT NULL,
    password VARCHAR2(100) NOT NULL,
    email VARCHAR2(100),
    full_name VARCHAR2(100),
    role VARCHAR2(50),
    enabled NUMBER(1) DEFAULT 1 NOT NULL,
    version NUMBER DEFAULT 0,
    CONSTRAINT uk_users_username UNIQUE (username),
    CONSTRAINT ck_users_enabled CHECK (enabled IN (0, 1)),
    CONSTRAINT ck_users_role CHECK (role IN ('SUPER_ADMIN', 'STAFF', 'CUSTOMER'))
);

