-- Create bookings table
CREATE TABLE bookings (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    seat_type_id NUMBER NOT NULL,
    booking_date TIMESTAMP NOT NULL,
    notes VARCHAR2(500),
    version NUMBER DEFAULT 0,
    CONSTRAINT fk_bookings_user_id FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_bookings_seat_type_id FOREIGN KEY (seat_type_id) REFERENCES seat_types(id)
);
